version: '3'

services:
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    volumes:
      - pgadmin:/data
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - db
    env_file:
      - ./.env
  parser:
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host ${APP_HOST} --reload"
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - ${APP_PORT}:8000
    depends_on:
      - db
  redis:
    image: redis
    restart: always
    ports:
      - ${REDIS_PORT}:6379
  celery:
    image: parser
    restart: always
    build: .
    command: celery -A app.worker.celery worker -l info
    volumes:
     - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - parser
  celery_beat:
    image: parser
    build: .
    restart: always
    command: celery -A app.worker.celery beat -l info
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - celery
  dashboard:
    image: parser
    command: celery --broker=redis://redis:6379/0 flower --port=5555 --address=0.0.0.0
    env_file:
      - ./.env
    ports:
      - ${FLOWER_PORT}:5555
    depends_on:
      - parser
      - redis
      - celery
volumes:
  postgres_data:
  pgadmin: