"""initial

Revision ID: 5cea67f38bd3
Revises: 
Create Date: 2023-03-31 03:28:59.431443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cea67f38bd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('flt', sa.Integer(), nullable=False),
    sa.Column('depdate', sa.Date(), nullable=False),
    sa.Column('dep', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_id'), 'flights', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flights_id'), table_name='flights')
    op.drop_table('flights')
    # ### end Alembic commands ###
