name: Code checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Install python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Deploy project
        run: |
          mv test_env .env
          docker compose up -d --build
      - name: Run flake8
        run: docker compose run parser flake8 .
      - name: Run mypy
        run: docker compose run parser mypy .
      - name: Run pytests
        run: docker compose run parser pytest .
